version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvnw package
